### ISSUE TITLE
Including 'placeholders.php' file, but it doesn't exist

### ISSUE THREAD

**Issue by arnons1** [pqina/snippy#1]
Starting 6 hours ago (with 1.3.0), snippy.php tries to include 'placeholders.php' which was deleted from the repository. This causes a 500 server error

**Comment by rikschennink** [comment]
Oh nuts! Pushed a new version this morning and indeed removed this file, I wasn’t aware it was still referenced somewhere (no errors thrown on my install somehow), will fix tomorrow morning.

**Comment by rikschennink** [comment]
@arnons1 Should be fixed now, sorry for the inconvenience.
