### ISSUE TITLE
No placeholders results in PHP error

### ISSUE THREAD

**Issue by michaelkrieger** [pqina/snippy#3]
When using a bit without any attributes (ie: [my_shortcode]), it displays the following:
```
Warning: array_merge(): Argument #1 is not an array in /.../wp-content/plugins/snippy/snippy.php on line 304
Warning: array_merge(): Argument #1 is not an array in /.../wp-content/plugins/snippy/snippy.php on line 307
```

Per the shortcode documentation "**$atts - an associative array of attributes, or an empty string if no attributes are given**" ( [Shortcode API](https://codex.wordpress.org/Shortcode_API) ) hence it's wrong to consider that $atts will always be an array. Since attributes are optional (ie: **[my_shortcode]** ), atts can be a blank string.

Adding this on line 304 fixes the issue
```
if (!is_array($atts)) $atts = array();
```
above these sections.

This started only since the last update.

**Comment by rikschennink** [comment]
@michaelkrieger Thanks for reporting Michael! Fixing it right now.

**Comment by rikschennink** [comment]
`1.3.2` should be up in a minute.
